# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sequel_migration_builder}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roland Swingler"]
  s.date = %q{2010-08-09}
  s.description = %q{Build Sequel Migrations based on the differences between two schemas}
  s.email = %q{roland.swingler@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/sequel/migration_builder.rb",
     "lib/sequel/schema/alter_table_operations.rb",
     "lib/sequel/schema/db_column.rb",
     "lib/sequel/schema/db_schema_parser.rb",
     "sequel_migration_builder.gemspec",
     "spec/alter_table_operations_spec.rb",
     "spec/db_column_spec.rb",
     "spec/db_schema_parser_spec.rb",
     "spec/migration_builder_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/knaveofdiamonds/sequel_migration_builder}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Build Sequel Migrations based on the differences between two schemas}
  s.test_files = [
    "spec/alter_table_operations_spec.rb",
     "spec/db_column_spec.rb",
     "spec/db_schema_parser_spec.rb",
     "spec/migration_builder_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 3.12.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<sequel>, [">= 3.12.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 3.12.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

