# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sequel_migration_builder 0.4.3 ruby lib

Gem::Specification.new do |s|
  s.name = "sequel_migration_builder"
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Roland Swingler"]
  s.date = "2014-09-08"
  s.description = "Build Sequel Migrations based on the differences between two schemas"
  s.email = "roland.swingler@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sequel/migration_builder.rb",
    "lib/sequel/schema/alter_table_operations.rb",
    "lib/sequel/schema/db_column.rb",
    "lib/sequel/schema/db_index.rb",
    "lib/sequel/schema/db_schema_parser.rb",
    "sequel_migration_builder.gemspec",
    "spec/alter_table_operations_spec.rb",
    "spec/db_column_spec.rb",
    "spec/db_index_spec.rb",
    "spec/db_schema_parser_spec.rb",
    "spec/migration_builder_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/knaveofdiamonds/sequel_migration_builder"
  s.rubygems_version = "2.2.1"
  s.summary = "Build Sequel Migrations based on the differences between two schemas"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 3.20.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<sequel>, [">= 3.20.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 3.20.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

